---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: manual-template
spec:
  params:
    - name: WORKSPACE_ID
      description: The workspace id
    - name: ibmcloud-api
      description: the ibmcloud api
      default: https://cloud.ibm.com
    - name: apikey
      description: the ibmcloud api key
    - name: git-token
      description: token to access the git repository
    - name: icr-pull-secret
      description: (optional) .dockerconfigjson (base64 encoded) used to access private ibm container registry
      default: "eyJhdXRocyI6e319Cg==" # {"auths":{}}
    - name: enable-automatic-plan-apply
      description: if true, a plan and apply will be automatically executed upon changes to the template code
      default: "true"
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: v1
      kind: Secret
      metadata:
        name: cd-secret
      type: Opaque
      stringData:
        API_KEY: $(params.apikey)
    - apiVersion: v1
      kind: Secret
      data:
        .dockerconfigjson: $(params.icr-pull-secret)
      metadata:
        name: icr-pull-secret
      type: kubernetes.io/dockerconfigjson
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: deploy-pipeline
        podTemplate:
          imagePullSecrets:
            - name: icr-pull-secret
        workspaces:
          - name: artifacts
            persistentVolumeClaim:
              claimName: pipelinerun-$(uid)-pvc
        params:
          - name: WORKSPACE_ID
            value: $(params.WORKSPACE_ID)
          - name: ibmcloud-api
            value: $(params.ibmcloud-api)
          - name: apikey
            value: $(params.apikey)
          - name: git-token
            value: $(params.git-token)
          - name: enable-automatic-plan-apply
            value: $(params.enable-automatic-plan-apply)
