properties:
  - type: text
    name: WORKSPACE_ID
    value: ${WORKSPACE_ID}
  - type: secure
    name: apikey
    value: ${API_KEY}
  - type: text
    name: ibmcloud-api
    value: ${IBM_CLOUD_API}
  - type: text
    name: enable-automatic-plan-apply
    value: ${ENABLE_PLAN_APPLY}
  - name: pipeline-debug
    type: single_select
    value:
      "0": true
      "1": false
triggers:
  - type: manual
    name: Manual Trigger - 0
    eventListener: manual-trigger-listener
  - type: git
    pattern: ${APP_BRANCH}
    events: { "push": true }
    name: Git Trigger - Commit
    eventListener: ${event-ci-listener-name}
    service: ${terraform-template}
inputs:
  - type: git
    path: .tekton
    branch: ${TEMPLATE_BRANCH}
    service: ${schematics-pipeline}
