---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: deploy-pipeline
spec:
  params:
    - name: WORKSPACE_ID
      description: workspace id
    - name: ibmcloud-api
      description: the ibmcloud api
      default: https://cloud.ibm.com
    - name: apikey
      description: the IBM Cloud API key
    - name: enable-automatic-plan-apply
      description: if true, a plan and apply will be automatically executed upon changes to the template code
    - name: TF_VAR_environment
      description: environment name
    - name: TF_VAR_project_name
      description: project name
    - name: TF_VAR_public_key
      description: ssh public key
    - name: TF_VAR_port
      description: service port
      default: 8080
  workspaces:
    - name: artifacts
  tasks:
    - name: update
      taskRef:
        name: update-task
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: WORKSPACE_ID
          value: $(params.WORKSPACE_ID)
        - name: ibmcloud-api
          value: $(params.ibmcloud-api)
        - name: apikey
          value: $(params.apikey)
        - name: enable-automatic-plan-apply
          value: $(params.enable-automatic-plan-apply)
        - name: TF_VAR_environment
          value: $(params.TF_VAR_environment)
        - name: TF_VAR_project_name
          value: $(params.TF_VAR_project_name)
        - name: TF_VAR_public_key
          value: $(params.TF_VAR_public_key)
        - name: TF_VAR_port
          value: $(params.TF_VAR_port)
    - name: plan
      runAfter: [update]
      taskRef:
        name: plan-task
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: WORKSPACE_ID
          value: $(params.WORKSPACE_ID)
        - name: ibmcloud-api
          value: $(params.ibmcloud-api)
        - name: apikey
          value: $(params.apikey)
        - name: enable-automatic-plan-apply
          value: $(params.enable-automatic-plan-apply)
    - name: apply
      runAfter: [plan]
      taskRef:
        name: apply-task
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: WORKSPACE_ID
          value: $(params.WORKSPACE_ID)
        - name: ibmcloud-api
          value: $(params.ibmcloud-api)
        - name: apikey
          value: $(params.apikey)
        - name: enable-automatic-plan-apply
          value: $(params.enable-automatic-plan-apply)
    - name: test
      runAfter: [apply]
      workspaces:
        - name: artifacts
          workspace: artifacts
      taskRef:
        name: test-task
      params:
        - name: WORKSPACE_ID
          value: $(params.WORKSPACE_ID)
        - name: ibmcloud-api
          value: $(params.ibmcloud-api)
        - name: apikey
          value: $(params.apikey)
        - name: enable-automatic-plan-apply
          value: $(params.enable-automatic-plan-apply)
